### ISSUE TITLE
data exchange between ROS and the microautobox

### ISSUE THREAD

**Issue by LisaWeichsel** [StanfordASL/safe_traffic_weaving#1]
Hi,
Your publication "On Infusing Reachability-Based SafetyAssurance within Probabilistic PlanningFrameworks for Human-Robot Vehicle Interactions" drew my attention to your code and your project.
I have a question about that: 
How did you realize the communication between the ROS network and the microautobox ? Did you use the Robotics System Toolbox from Mathworks ?

Regards, 
Lisa

**Comment by schmrlng** [comment]
Hi Lisa,

We have a ROS node that serves as an interface between the world of ROS pub/sub (where all of our high level decision making and MPC control code runs within other nodes) and the microautobox (running a MATLAB Simulink model that integrates all of the sensor info into the vehicle state and executes the low level control). This "auto_bridge" node runs on a standard computer and translates ROS messages into UDP packets sent to the microautobox and vice versa at 100Hz (message receipt is verified through a heartbeat protocol). Messages sent to the microautobox consist of vehicle control signals, and messages coming from the microautobox consist of vehicle state information.

Unfortunately this code, in particular the simulink model, is rather specific to our experimental platform and lives in a different/difficult to expose repository. In any case I am happy to share additional architectural details if you have any more specific questions.

Cheers,
Ed
